name: Node.js CI

on:
  schedule:
    - cron: "0,5 * * * *"
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '18.x', '19.x', '20.x', '21.x', '22.x' ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i if-thursday
